[wokwi]
version = 1
firmware = '.esphome/build/dut/.pioenvs/dut/firmware.bin'
elf = '.esphome/build/dut/.pioenvs/dut/firmware.elf'

# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi

[[chip]]
name = "chip"
binary = "chip/chip.wasm"
